# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RECARGA.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_APP_recarga(object):
    def setupUi(self, APP_recarga):
        APP_recarga.setObjectName("APP_recarga")
        APP_recarga.resize(750, 550)
        APP_recarga.setMinimumSize(QtCore.QSize(750, 550))
        APP_recarga.setMaximumSize(QtCore.QSize(750, 560))
        APP_recarga.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        APP_recarga.setFont(font)
        APP_recarga.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(APP_recarga)
        self.centralwidget.setObjectName("centralwidget")
        self.grupo1_frame = QtWidgets.QFrame(self.centralwidget)
        self.grupo1_frame.setGeometry(QtCore.QRect(0, 0, 801, 311))
        self.grupo1_frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.grupo1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grupo1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grupo1_frame.setObjectName("grupo1_frame")
        self.saldo_actual_label = QtWidgets.QLabel(self.grupo1_frame)
        self.saldo_actual_label.setGeometry(QtCore.QRect(260, 50, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.saldo_actual_label.setFont(font)
        self.saldo_actual_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.saldo_actual_label.setObjectName("saldo_actual_label")
        self.r_saldo_act_label = QtWidgets.QLabel(self.grupo1_frame)
        self.r_saldo_act_label.setGeometry(QtCore.QRect(120, 90, 521, 81))
        font = QtGui.QFont()
        font.setFamily("BrowalliaUPC")
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.r_saldo_act_label.setFont(font)
        self.r_saldo_act_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_saldo_act_label.setStyleSheet("color: rgb(0, 170, 0);")
        self.r_saldo_act_label.setText("")
        self.r_saldo_act_label.setScaledContents(True)
        self.r_saldo_act_label.setAlignment(QtCore.Qt.AlignCenter)
        self.r_saldo_act_label.setObjectName("r_saldo_act_label")
        self.uid_label = QtWidgets.QLabel(self.grupo1_frame)
        self.uid_label.setGeometry(QtCore.QRect(530, 20, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.uid_label.setFont(font)
        self.uid_label.setObjectName("uid_label")
        self.r_uid_label = QtWidgets.QLabel(self.grupo1_frame)
        self.r_uid_label.setGeometry(QtCore.QRect(599, 20, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.r_uid_label.setFont(font)
        self.r_uid_label.setStyleSheet("color: rgb(0, 85, 255);")
        self.r_uid_label.setText("")
        self.r_uid_label.setObjectName("r_uid_label")
        self.saldo_restante_label = QtWidgets.QLabel(self.grupo1_frame)
        self.saldo_restante_label.setGeometry(QtCore.QRect(260, 200, 191, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.saldo_restante_label.setFont(font)
        self.saldo_restante_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.saldo_restante_label.setScaledContents(True)
        self.saldo_restante_label.setAlignment(QtCore.Qt.AlignCenter)
        self.saldo_restante_label.setObjectName("saldo_restante_label")
        self.re_line = QtWidgets.QLineEdit(self.grupo1_frame)
        self.re_line.setGeometry(QtCore.QRect(220, 250, 281, 41))
        self.re_line.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.re_line.setFont(font)
        self.re_line.setTabletTracking(True)
        self.re_line.setAcceptDrops(False)
        self.re_line.setAutoFillBackground(True)
        self.re_line.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        self.re_line.setInputMask("")
        self.re_line.setText("")
        self.re_line.setMaxLength(32767)
        self.re_line.setCursorPosition(0)
        self.re_line.setAlignment(QtCore.Qt.AlignCenter)
        self.re_line.setDragEnabled(False)
        self.re_line.setPlaceholderText("")
        self.re_line.setClearButtonEnabled(True)
        self.re_line.setObjectName("re_line")
        self.Button_proc = QtWidgets.QPushButton(self.grupo1_frame)
        self.Button_proc.setGeometry(QtCore.QRect(610, 250, 111, 31))
        self.Button_proc.setObjectName("Button_proc")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 320, 801, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 150, 121, 27))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 20))
        self.pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.aviso_label = QtWidgets.QLabel(self.frame)
        self.aviso_label.setGeometry(QtCore.QRect(20, 10, 711, 101))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.aviso_label.setFont(font)
        self.aviso_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.aviso_label.setText("")
        self.aviso_label.setAlignment(QtCore.Qt.AlignCenter)
        self.aviso_label.setObjectName("aviso_label")
        self.time_c_label = QtWidgets.QLabel(self.frame)
        self.time_c_label.setGeometry(QtCore.QRect(150, 130, 271, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.time_c_label.setFont(font)
        self.time_c_label.setText("")
        self.time_c_label.setObjectName("time_c_label")
        self.time_c_label_2 = QtWidgets.QLabel(self.frame)
        self.time_c_label_2.setGeometry(QtCore.QRect(430, 130, 101, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.time_c_label_2.setFont(font)
        self.time_c_label_2.setText("")
        self.time_c_label_2.setObjectName("time_c_label_2")
        self.frame.raise_()
        self.grupo1_frame.raise_()
        APP_recarga.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(APP_recarga)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        APP_recarga.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(APP_recarga)
        self.statusbar.setObjectName("statusbar")
        APP_recarga.setStatusBar(self.statusbar)
        self.actionDetener = QtWidgets.QAction(APP_recarga)
        self.actionDetener.setObjectName("actionDetener")
        self.actionAyuda = QtWidgets.QAction(APP_recarga)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionSalir = QtWidgets.QAction(APP_recarga)
        self.actionSalir.setObjectName("actionSalir")
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionDetener)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionAyuda)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSalir)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(APP_recarga)
        QtCore.QMetaObject.connectSlotsByName(APP_recarga)

    def retranslateUi(self, APP_recarga):
        _translate = QtCore.QCoreApplication.translate
        APP_recarga.setWindowTitle(_translate("APP_recarga", "MainWindow"))
        self.saldo_actual_label.setText(_translate("APP_recarga", "<html><head/><body><p align=\"center\">Saldo:</p></body></html>"))
        self.uid_label.setText(_translate("APP_recarga", "UID:"))
        self.saldo_restante_label.setText(_translate("APP_recarga", "Recarga:"))
        self.Button_proc.setText(_translate("APP_recarga", "PROCESAR"))
        self.pushButton.setText(_translate("APP_recarga", "RECARGAR"))
        self.menuMenu.setTitle(_translate("APP_recarga", "Menu"))
        self.actionDetener.setText(_translate("APP_recarga", "Detener"))
        self.actionAyuda.setText(_translate("APP_recarga", "Ayuda"))
        self.actionSalir.setText(_translate("APP_recarga", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    APP_recarga = QtWidgets.QMainWindow()
    ui = Ui_APP_recarga()
    ui.setupUi(APP_recarga)
    APP_recarga.show()
    sys.exit(app.exec_())
